# Generated by Django 2.1.6 on 2019-08-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simlr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
